---
deployment:
  tasks:
    - export FRONTEND=/home/web3605/public_html/
    - /bin/cp -R ./client/build/static $FRONTEND
    - /bin/cp ./client/build/.htaccess $FRONTEND
    - /bin/cp ./client/build/asset-manifest.json $FRONTEND
    - /bin/cp ./client/build/favicon.ico $FRONTEND
    - /bin/cp ./client/build/index.html $FRONTEND
    - /bin/cp ./client/build/logo192.png $FRONTEND
    - /bin/cp ./client/build/logo512.png $FRONTEND
    - /bin/cp ./client/build/manifest.json $FRONTEND
    - /bin/cp ./client/build/robots.txt $FRONTEND

    - export BACKEND=/home/web3605/back_end/
    - /bin/cp -R ./server/config $BACKEND
    - /bin/cp -R ./server/controllers $BACKEND
    - /bin/cp -R ./server/db $BACKEND
    - /bin/cp -R ./server/models $BACKEND
    - /bin/cp -R ./server/utils $BACKEND
    - /bin/cp -R ./server/package.json $BACKEND
    - /bin/cp -R ./server/server.js $BACKEND